import { getParserFromInput } from "@griffithswaite/ts-plsql-parser";
import { isTableAllowed, normalizeIdentifier, parseIdentifierTokensReference } from "./tools/allowlist";

type ParseTreeNode = {
	children?: ParseTreeNode[];
	constructor?: { name?: string };
	getText?: () => string;
};

// Context names generated by the Oracle PL/SQL ANTLR grammar.
const WRITE_CONTEXTS = new Map<string, string>([
	["Insert_statementContext", "INSERT"],
	["Update_statementContext", "UPDATE"],
	["Delete_statementContext", "DELETE"],
	["Merge_statementContext", "MERGE"],
]);

const EXEC_CONTEXTS = new Map<string, string>([
	["Call_statementContext", "CALL"],
	["Execute_immediateContext", "EXECUTE"],
	["Anonymous_blockContext", "BEGIN"],
]);

/** Result of SQL validation — either a pass or a rejection with a human-readable reason. */
export type ValidationResult =
 | { valid: true }
 | { valid: false; reason: string };

function contextName(node: ParseTreeNode | null | undefined): string {
	return node?.constructor?.name ?? "";
}

function firstContextChild(node: ParseTreeNode | null | undefined): ParseTreeNode | null {
	if (!node?.children) {
		return null;
	}

	for (const child of node.children) {
		if (contextName(child).endsWith("Context")) {
			return child;
		}
	}

	return null;
}

function walkTree(
	node: ParseTreeNode | null | undefined,
	path: string,
	visit: (node: ParseTreeNode, path: string) => string | null
): string | null {
	if (!node) {
		return null;
	}

	const hit = visit(node, path);
	if (hit) {
		return hit;
	}

	const children = node.children ?? [];
	for (let i = 0; i < children.length; i++) {
		const child = children[i];
		const childHit = walkTree(child, `${path}.children[${i}]`, visit);
		if (childHit) {
			return childHit;
		}
	}

	return null;
}

function toStatementType(contextType: string): string {
	if (!contextType) {
		return "UNKNOWN";
	}

	if (contextType.startsWith("Create_")) {
		return "CREATE";
	}
	if (contextType.startsWith("Drop_")) {
		return "DROP";
	}
	if (contextType.startsWith("Alter_")) {
		return "ALTER";
	}
	if (contextType === "Truncate_tableContext" || contextType === "Truncate_clusterContext") {
		return "TRUNCATE";
	}
	if (contextType === "Rename_objectContext") {
		return "RENAME";
	}
	if (contextType === "Call_statementContext") {
		return "CALL";
	}
	if (contextType === "Execute_immediateContext") {
		return "EXECUTE";
	}
	if (contextType === "Anonymous_blockContext") {
		return "BEGIN";
	}
	if (contextType === "Insert_statementContext") {
		return "INSERT";
	}
	if (contextType === "Update_statementContext") {
		return "UPDATE";
	}
	if (contextType === "Delete_statementContext") {
		return "DELETE";
	}
	if (contextType === "Merge_statementContext") {
		return "MERGE";
	}
	if (contextType === "Select_statementContext" || contextType === "Select_only_statementContext") {
		return "SELECT";
	}

	return contextType
		.replace(/Context$/, "")
		.replace(/([a-z0-9])([A-Z])/g, "$1_$2")
		.toUpperCase();
}

function classifyRootStatementType(unitStatement: ParseTreeNode): string {
	const unitChild = firstContextChild(unitStatement);
	const unitChildType = contextName(unitChild);

	if (unitChildType === "Data_manipulation_language_statementsContext") {
		const dmlChild = firstContextChild(unitChild);
		return toStatementType(contextName(dmlChild));
	}

	return toStatementType(unitChildType);
}

function extractTableReferences(unitStatement: ParseTreeNode): Array<{ full: string; owner?: string; table: string; dblink?: string }> {
	const tableNames = new Map<string, { full: string; owner?: string; table: string; dblink?: string }>();
	const cteNames = new Set<string>();

	walkTree(unitStatement, "root", (node) => {
		const type = contextName(node);
		const text = node.getText?.() ?? "";
		const normalized = normalizeIdentifier(text);

		if (!normalized) {
			return null;
		}

		if (type === "Query_nameContext") {
			cteNames.add(normalized);
		}

		if (type === "Tableview_nameContext") {
			const parsed = parseIdentifierTokensReference(text);
			if (parsed) {
				tableNames.set(normalized, parsed);
			}
		}

		return null;
	});

	return [...tableNames.values()].filter((tableRef) => !cteNames.has(tableRef.full));
}

function findForbiddenOperation(unitStatement: ParseTreeNode): string | null {
	return walkTree(unitStatement, "root", (node, path) => {
		const type = contextName(node);

		const writeType = WRITE_CONTEXTS.get(type);
		if (writeType) {
			return `Query contains a write operation (${writeType}) at ${path}`;
		}

		if (
			type.startsWith("Create_") ||
			type.startsWith("Drop_") ||
			type.startsWith("Alter_") ||
			type === "Truncate_tableContext" ||
			type === "Truncate_clusterContext" ||
			type === "Rename_objectContext"
		) {
			return `Query contains a DDL operation (${toStatementType(type)}) at ${path}`;
		}

		if (type === "For_update_clauseContext") {
			return `Query contains a row-locking clause (FOR UPDATE) at ${path}`;
		}

		const execType = EXEC_CONTEXTS.get(type);
		if (execType) {
			return `Query contains a procedural execution (${execType}) at ${path}`;
		}

		return null;
	});
}

/**
 * Validates a SQL string for safe read-only execution.
 * Parses into a syntax tree, enforces single SELECT, walks for write/DDL/exec nodes,
 * and checks table references against the allowlist when provided.
 * @param sql - The raw SQL string to validate.
 * @param allowlist - Optional list of permitted table names. When provided (even if empty), only listed tables are allowed.
 * @param defaultSchema - Optional default schema used to scope unqualified allowlist entries.
 */
export function validateQuery(
	sql: string,
	allowlist?: string[],
	defaultSchema?: string
): ValidationResult {
	const parser = getParserFromInput(sql) as {
		removeErrorListeners?: () => void;
		_syntaxErrors?: number;
		numberOfSyntaxErrors?: number;
		sql_script: () => ParseTreeNode;
	};

	// Keep the validator quiet and rely on explicit rejection messages.
	parser.removeErrorListeners?.();

	// Step 1 - Parse
	let tree: ParseTreeNode;
	try {
		tree = parser.sql_script();
	}
	catch {
		return { valid: false, reason: "Query could not be parsed. Ensure it is valid SQL." };
	}

	const syntaxErrors = parser.numberOfSyntaxErrors ?? parser._syntaxErrors ?? 0;
	if (syntaxErrors > 0) {
		return { valid: false, reason: "Query could not be parsed. Ensure it is valid SQL." };
	}

	// Step 2 - Must be a single statement
	const unitStatements = (tree.children ?? []).filter(
		(child) => contextName(child) === "Unit_statementContext"
	);
	if (unitStatements.length !== 1) {
		return { valid: false, reason: "Multiple statements are not permitted. Submit one SELECT at a time" };
	}

	// Step 3 - Root statement must be SELECT
	const rootStatement = unitStatements[0];
	if (!rootStatement) {
		return { valid: false, reason: "Query could not be parsed. Ensure it is valid SQL." };
	}

	const rootType = classifyRootStatementType(rootStatement);
	if (rootType !== "SELECT") {
		return {
			valid: false,
			reason: `Statement type ${rootType} is not permitted. Only SELECT statements are allowed.`,
		};
	}

	// Step 4-6 - Walk the full parse tree for any forbidden operations
	const violation = findForbiddenOperation(rootStatement);
	if (violation) {
		return { valid: false, reason: violation };
	}

	// Step 7 - Allowlist check if provided
	if (allowlist) {
		const tableReferences = extractTableReferences(rootStatement);
		for (const tableRef of tableReferences) {
			if (!isTableAllowed(allowlist, tableRef.table, tableRef.owner, defaultSchema, tableRef.dblink)) {
				const allowedTables = allowlist.length > 0 ? allowlist.join(", ") : "(none)";
				return {
					valid: false,
					reason: `Query references table ${tableRef.full} which is not in the allowlist for this environment. Allowed tables: ${allowedTables}.`
				};
			}
		}
	}

	return {valid: true};
}
